export const satcActivities = [
  {
    id: "satc-001",
    title: "Two-Minute Reset",
    category: "calm",
    durationMinutes: 2,
    prompt: "Sit comfortably, relax your shoulders, and take ten slow breaths.",
    materials: [],
    reflectionQuestion: "How does your body feel compared with when you started?",
  },
  {
    id: "satc-002",
    title: "Desk Stretch",
    category: "movement",
    durationMinutes: 3,
    prompt: "Stretch your neck, wrists, shoulders, and back while staying seated.",
    materials: [],
    reflectionQuestion: "Which stretch helped you feel the most awake?",
  },
  {
    id: "satc-003",
    title: "Gratitude List",
    category: "reflection",
    durationMinutes: 4,
    prompt: "Write down three things that are going well today.",
    materials: ["paper", "pen"],
    reflectionQuestion: "What is one thing you want to remember from your list?",
  },
  {
    id: "satc-004",
    title: "Hydration Break",
    category: "wellness",
    durationMinutes: 2,
    prompt: "Drink a glass of water and notice how you feel afterward.",
    materials: ["water"],
    reflectionQuestion: "Do you feel any different after taking this break?",
  },
  {
    id: "satc-005",
    title: "Five-Senses Check-In",
    category: "mindfulness",
    durationMinutes: 5,
    prompt: "Name five things you see, four you feel, three you hear, two you smell, and one you taste.",
    materials: [],
    reflectionQuestion: "Which sense was easiest for you to notice?",
  },
  {
    id: "satc-006",
    title: "Quick Walk",
    category: "movement",
    durationMinutes: 5,
    prompt: "Walk around the room, hallway, or outside at an easy pace.",
    materials: [],
    reflectionQuestion: "Did moving around change your energy level?",
  },
  {
    id: "satc-007",
    title: "Brain Dump",
    category: "focus",
    durationMinutes: 5,
    prompt: "Write every task or worry on your mind without organizing it yet.",
    materials: ["paper", "pen"],
    reflectionQuestion: "What is one item you can handle next?",
  },
  {
    id: "satc-008",
    title: "Positive Message",
    category: "connection",
    durationMinutes: 3,
    prompt: "Send a kind message or thank-you note to someone.",
    materials: ["phone or computer"],
    reflectionQuestion: "How did it feel to reach out?",
  },
  {
    id: "satc-009",
    title: "Room Refresh",
    category: "environment",
    durationMinutes: 5,
    prompt: "Clear one small surface, throw away trash, or reset your workspace.",
    materials: [],
    reflectionQuestion: "What changed in your space after five minutes?",
  },
  {
    id: "satc-010",
    title: "Tiny Creative Sprint",
    category: "creative",
    durationMinutes: 5,
    prompt: "Sketch, doodle, write a sentence, or make something small without judging it.",
    materials: ["paper", "pen"],
    reflectionQuestion: "What did you make, and what did you notice while making it?",
  },
];
